// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSpfP4MWNQQZ_ax3AlRNerMpNMKK1UCA',
    appId: '1:753060468997:web:21872e163494ce8eda7f6c',
    messagingSenderId: '753060468997',
    projectId: 'recipe-food-c74ff',
    authDomain: 'recipe-food-c74ff.firebaseapp.com',
    storageBucket: 'recipe-food-c74ff.firebasestorage.app',
    measurementId: 'G-Z9NSRQ1VS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrIaPoLcDp2DeFITWQDdYdV-BoexTetSs',
    appId: '1:753060468997:android:5a0ec77a2f7947c4da7f6c',
    messagingSenderId: '753060468997',
    projectId: 'recipe-food-c74ff',
    storageBucket: 'recipe-food-c74ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5LF0baZ2nZx2nm3HSJNQksFpZvX0ld_o',
    appId: '1:753060468997:ios:641103ac6b9a3a3eda7f6c',
    messagingSenderId: '753060468997',
    projectId: 'recipe-food-c74ff',
    storageBucket: 'recipe-food-c74ff.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipes',
  );

}