// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMuZ4wsamwSXCkTbSP-ho1snXeEQ78C4',
    appId: '1:927317411598:web:7d605e697f2145a5fe795f',
    messagingSenderId: '927317411598',
    projectId: 'food-recipes-1b74a',
    authDomain: 'food-recipes-1b74a.firebaseapp.com',
    storageBucket: 'food-recipes-1b74a.firebasestorage.app',
    measurementId: 'G-GSWSN5EXH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLEkw_nEMectGuAkWtCdmY8FqrrAFuQU',
    appId: '1:927317411598:android:fd96f567624761a1fe795f',
    messagingSenderId: '927317411598',
    projectId: 'food-recipes-1b74a',
    storageBucket: 'food-recipes-1b74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_yfUwiY6b07sl64AiCz6fSzvfF0KvgE',
    appId: '1:927317411598:ios:0fa9a68cd48864affe795f',
    messagingSenderId: '927317411598',
    projectId: 'food-recipes-1b74a',
    storageBucket: 'food-recipes-1b74a.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipes',
  );
}
